//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PryFincasCafeteras.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FincaAsociado
    {
        public int IdFinca { get; set; }
        public int IdAsociado { get; set; }
        public string rol { get; set; }
    
        public virtual Asociado Asociado { get; set; }
        public virtual Finca Finca { get; set; }
    }
}
