//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PryFincasCafeteras.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FincasCafeterasCon : DbContext
    {
        public FincasCafeterasCon()
            : base("name=FincasCafeterasCon")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Asociado> Asociado { get; set; }
        public virtual DbSet<Departamento> Departamento { get; set; }
        public virtual DbSet<Finca> Finca { get; set; }
        public virtual DbSet<FincaAsociado> FincaAsociado { get; set; }
        public virtual DbSet<Municipio> Municipio { get; set; }
        public virtual DbSet<Trabajador> Trabajador { get; set; }
        public virtual DbSet<Vereda> Vereda { get; set; }
    }
}
